# Generated by Django 3.2.13 on 2022-05-05 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0003_alter_blogcategory_blogcategoryid'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='isdelete',
            field=models.BooleanField(default=False),
        ),
    ]
